/*

 PKMN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 20
   Tile set      : C:\Users\brandon\Desktop\gbtd22\pokemon.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_dataWidth 40
#define map_dataHeight 20
#define map_dataBank 0

extern unsigned char map_data[];

/* End of PKMN_MAP.H */
